name: publish
'on':
  - push
jobs:
  publish-hello-docker-image:
    permissions: write-all
    name: Publish Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: '${{ github.actor }}'
          password: '${{ secrets.GITHUB_TOKEN }}'
      - name: Build the cordova Docker image
        run: |
          docker build . --tag ghcr.io/mena97villalobos/cordova:latest
          docker run ghcr.io/mena97villalobos/cordova:latest
          docker push ghcr.io/mena97villalobos/cordova:latest
